pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/karishmagdly27/demo-pro1.git'
            }
        }

        stage('Deploy App') {
            steps {
                sshagent(['app-server-key']) {
                    sh '''
                    # Create deployment directory if not exists
                    ssh -o StrictHostKeyChecking=no ubuntu@18.118.104.14 "mkdir -p /opt/demo_app"

                    # Copy files
                    scp -r * ubuntu@18.118.104.14:/opt/demo_app/

                    # Restart Nginx to serve new app
                    ssh -o StrictHostKeyChecking=no ubuntu@18.118.104.14 "sudo systemctl restart nginx"

                    # Verify Nginx is running
                    ssh -o StrictHostKeyChecking=no ubuntu@18.118.104.14 "systemctl status nginx | grep 'active (running)'"
                    '''
                }
            }
        }

        stage('Success') {
            steps {
                echo 'App deployed successfully and Nginx restarted!'
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished.'
        }
    }
}
